### ISSUE TITLE
[No.10]Support for user customization of plots displayed on the website

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#351]
## Requirement

Plot images and statistical data posted on the optinist-for-server website, To provide documentation of the customization procedure and adjustments to the system to allow users (non-IT engineers and data researchers) to easily customize the above posted data.

- Supplemental
  - GUI-based customization of displayed data is out of scope.
    - Since the user analysis algorithm is implemented in python code, the customization of the display data may be done by editing the python code as well.
    - However, the customization method should be as user-friendly as possible.

### related docs

- requirement
  - https://drive.google.com/file/d/1FTb2BFeDtG4FaN2Dj2IKrTsKjqLMAUs_/view
    - No.4
- notes considered
  - https://drive.google.com/file/d/1sj_yqwqufpFvZLa7EPkg26F3pGXkaDA9/view

##### Plot images (right side from `pixel image`)

![image](https://github.com/user-attachments/assets/4a553e58-8e45-4cd6-9b65-7993ef96def4)

- Header column
  - API
    - `GET /public/experiments`
      - `header.graph_titles`
  - Definition Location
    - `studio.app.optinist.routers.expdb.EXPERIMENT_GRAPHS`
- Plot URL
  - API response
    - `GET /public/experiments`
      - `items.graph_urls`
  - Definition Location
    - `studio.app.optinist.routers.expdb.get_experiment_urls`

##### Plot Images (right side from `Cell Mask`)

![image](https://github.com/user-attachments/assets/3beecaa9-cd70-4812-9dc1-8dcc9aca6d09)

- Header columns
  - API response
    - `GET /public/cells`
      - `header.graph_titles`
  - Definition Location
    - `studio.app.optinist.routers.expdb.CELL_GRAPHS`
- Plot URL
  - API Response
    - `GET /public/cells`
      - `items.graph_urls`
  - Definition Location
    - `studio.app.optinist.routers.expdb.expdbcell_transformer`

##### Statistics (right side from Plot Images)

![image](https://github.com/user-attachments/assets/ba3a21ae-526d-437b-97f9-79d2a26c7e89)

- API Response
  - `GET /public/cells`
    - `items.statistics`
- Definition Location
  - `studio.app.optinist.routers.expdb.get_cell_urls`

#### Flow of data generation

The data creation process consists of the following batch processes.

- Flow of data generation
  1. The data to be processed is input into the specified directory (env:EXPDB_DIR).
  2. The following BATCH program detects data input.
      ``` 
      python run_expdb_batch.py -o 1
      ``` 
  3. Each analysis result data is generated.

#### Plot Images generation location

- studio.app.optinist.core.expdb.batch_runner.\_\_process_dataset_registration
  ```
  expdb_batch.generate_plots(stat_data=stat_data)
  expdb_batch.generate_cellmasks()
  expdb_batch.generate_pixelmaps()
  ```
  - [ ] Check to see if there are any other leaks

#### Cells Statistics generation location

- studio.app.optinist.core.expdb.crud_cells.bulk_insert_cells
  ```
  bulk_insert_cells(db, exp.id, stat_data)
  ```

### Code modification

- 1. Configuration part
    - [ ] Put each constant that can be edited by users into an external file (yaml)
- 2. Code implementation part
    - [ ] 1. Simplify the method of adding output destinations for plot images
    - [ ] 2. Simplify the method of adding output destinations for statistics
    - \*If there are any improvement proposals to make it easier for users (non-IT engineers) to edit, apply them
    - \*Cutting out code that may be edited by users into dedicated modules, etc.

### Documentation

- [ ] To the Experiments/Cells View
  - [ ] Procedure for updating the header information of the view
  - [ ] Procedure for adding an output destination for plot images
  - [ ] Procedure for adding an output destination for statistics

**Comment by itutu-tienday** [comment]
Scope of request to developer

- Request for 1. of `Code modification`.
- For 2. and 3. of “Code modification”, please make a proposal once.
  - Request implementation depending on the result of the proposal.
- For “Documentation”, we would like to discuss the scope of response based on the proposal.

**Comment by tuanna26** [comment]
### Implementation plan for your requirements:
- Migrate CELL_GRAPHS and EXPERIMENT_GRAPHS into YAML. Update the backend code to read configuration settings directly from the YAML file.
- Returns the configuration via API, enabling the frontend to dynamically adapt the display based on the YAML settings
- Users can modify the YAML file by adding, updating, or removing entries or simply comment/uncomment sections to customize which columns or data points are displayed.

### Some suggestions to increase user experience:
- Implement a Python or Bash script
- Develop an API and a UI for authorized users

Above proposal remove the need for manual file edits and provides a more seamless and intuitive experience. The configuration can be stored in YAML file or database.

**Comment by tuanna26** [comment]
### Implementation plan for your requirements:

-  Migrate CELL_GRAPHS and EXPERIMENT_GRAPHS into YAML. Update the backend code to read configuration settings directly from the YAML 
- Return the configuration via API, enabling the frontend to dynamically adapt the display based on the YAML settings
- Users can modify the YAML file by adding, updating, or removing entries or simply comment/uncomment sections to customize which columns or data points are displayed.

### Some suggestions to increase user experience:

- Implement a Python or Bash script
- Develop an API and a UI for authorized users

Above proposals remove the need for manual file edits and provide a more seamless and intuitive experience. The configuration can be stored in YAML file or database.

**Comment by milesAraya** [comment]
One yaml for all or multiple yaml for each parameter type?

**Comment by milesAraya** [comment]
markdown file for walkthrough
https://drive.google.com/file/d/13ZSXFWDObqga593mI-b7U-icXGQ4X0WC/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@milesAraya 

> markdown file for walkthrough

The basic content and format seem to be OK.
Therefore, let's prepare public documentation (Wiki).
